### PR TITLE
Added Python3 compatibility

### PR DESCRIPTION
**Pull request by Mister-X-**
I'd like to preface I'm no expert in python. I used 2to3 to make it easier to convert, and adjusted a bit to make it work with both v2 and v3.

### CODE REVIEW

**Comment by 6e726d** [comment]
Before doing this merge I need to verify Impacket support for Python 3.

**Comment by kimocoder** [comment]
impacket should now support python3.

take a look at
https://github.com/SecureAuthCorp/impacket/commits/master

**Comment by 6e726d** [comment]
> impacket should now support python3.
> 
> take a look at
> https://github.com/SecureAuthCorp/impacket/commits/master

I know it's taking too long, but I'm working on this issue.

**Comment by 6e726d** [comment]
I'm ashamed and really sorry that this replay took me more than 2 years.

I'm actively working on making the tool work with Python 3, some fixes from @Mister-X- worked fine but other stuff was missing.

I will close this issue and finish the refactoring in the following weeks.

**Pull request closed without merging**
